-- Enable UUID extension
create extension if not exists "uuid-ossp";

create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  name text,
  avatar_url text,
  help_count int default 0,
  rating float default 5.0,
  
  constraint username_length check (char_length(name) >= 3)
);

alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

create table help_requests (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  requester_id uuid references profiles(id) not null,
  title text not null,
  description text not null,
  category text not null,
  urgency text not null,
  lat float not null,
  lng float not null,
  location_name text,
  status text default 'open',
  ai_relevance_score float default 0.0
);

alter table help_requests enable row level security;

create policy "Help requests are viewable by everyone."
  on help_requests for select
  using ( true );

create policy "Authenticated users can create requests."
  on help_requests for insert
  with check ( auth.role() = 'authenticated' );

create policy "Users can update their own requests."
  on help_requests for update
  using ( auth.uid() = requester_id );

create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'name', 'https://i.pravatar.cc/150?u=' || new.id);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
