
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:geolocator/geolocator.dart';
import '../../components/custom_textfield.dart';
import '../../components/primary_button.dart';
import '../../theme/app_theme.dart';
import '../../models/models.dart';
import '../../services/supabase_service.dart';

class CreateRequestScreen extends StatefulWidget {
  const CreateRequestScreen({super.key});

  @override
  State<CreateRequestScreen> createState() => _CreateRequestScreenState();
}

class _CreateRequestScreenState extends State<CreateRequestScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descController = TextEditingController();
  
  HelpCategory? _selectedCategory;
  UrgencyLevel _selectedUrgency = UrgencyLevel.medium;
  bool _isCategorizing = false;
  bool _isLoading = false;
  LocationPermission? _permission;

  @override
  void initState() {
    super.initState();
    _checkPermission();
  }

  Future<void> _checkPermission() async {
    bool serviceEnabled = await Geolocator.isLocationServiceEnabled();
    if (!serviceEnabled) return;

    LocationPermission permission = await Geolocator.checkPermission();
    if (permission == LocationPermission.denied) {
      permission = await Geolocator.requestPermission();
    }
    setState(() => _permission = permission);
  }

  // Mock auto-categorization based on title/desc
  void _detectCategory() async {
    final text = '${_titleController.text} ${_descController.text}'.toLowerCase();
    if (text.length < 5) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please enter more details to auto-categorize.')),
      );
      return;
    }

    setState(() => _isCategorizing = true);
    await Future.delayed(const Duration(milliseconds: 1500)); // Simulate UI delay
    
    if (!mounted) return;

    HelpCategory? detected;
    if (text.contains('leak') || text.contains('water') || text.contains('fire')) {
      detected = HelpCategory.emergency;
    } else if (text.contains('computer') || text.contains('wifi') || text.contains('phone')) {
      detected = HelpCategory.techSupport;
    } else if (text.contains('math') || text.contains('teach') || text.contains('tutor')) {
      detected = HelpCategory.education;
    } else if (text.contains('clean') || text.contains('move') || text.contains('fix')) {
      detected = HelpCategory.household;
    }

    if (detected != null) {
      setState(() {
        _selectedCategory = detected;
        _isCategorizing = false;
      });
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Row(
            children: [
              const Icon(Icons.auto_awesome, color: Colors.white, size: 16),
              const SizedBox(width: 8),
              Text('Auto-categorized as ${_categoryName(detected)}'),
            ],
          ),
          backgroundColor: AppColors.secondaryLight,
          behavior: SnackBarBehavior.floating,
        ),
      );
    } else {
      setState(() => _isCategorizing = false);
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Could not auto-categorize. Please select manually.')),
      );
    }
  }

  void _submitRequest() async {
    if (_formKey.currentState!.validate() && _selectedCategory != null) {
      setState(() => _isLoading = true);
      try {
        Position position;
        try {
          position = await Geolocator.getCurrentPosition();
        } catch (e) {
          position = Position(longitude: -122.4194, latitude: 37.7749, timestamp: DateTime.now(), accuracy: 0, altitude: 0, heading: 0, speed: 0, speedAccuracy: 0, altitudeAccuracy: 0, headingAccuracy: 0); // Fallback if location fails
        }

        final newRequest = HelpRequest(
          id: '', // Generated by DB
          requesterId: '', // Handled by Service
          requesterName: '', // Handled by DB join/Service
          requesterAvatarUrl: '', 
          title: _titleController.text,
          description: _descController.text,
          category: _selectedCategory!,
          urgency: _selectedUrgency,
          postedAt: DateTime.now(),
          distance: '', // Calc by DB/Client
          aiRelevanceScore: 0, 
          locationName: 'Current Location', 
          lat: position.latitude,
          lng: position.longitude,
          status: RequestStatus.open,
        );

        await SupabaseService().createHelpRequest(newRequest);

        if (mounted) {
          context.pop();
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Request posted successfully!')),
          );
        }
      } catch (e) {
        if (mounted) {
           ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Error: $e'), backgroundColor: Colors.red),
          );
        }
      } finally {
        if (mounted) setState(() => _isLoading = false);
      }
    } else if (_selectedCategory == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select a category')),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('New Request', style: GoogleFonts.poppins(fontWeight: FontWeight.bold)),
        leading: IconButton(
          icon: const Icon(Icons.close),
          onPressed: () => context.pop(),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _buildSectionTitle('What do you need help with?'),
              const SizedBox(height: 8),
              CustomTextField(
                hintText: 'Title (e.g., Leaky Faucet)',
                controller: _titleController,
                validator: (v) => v!.isEmpty ? 'Required' : null,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _descController,
                maxLines: 4,
                onChanged: (_) {
                  // Debounce could be added here
                  if (_titleController.text.isNotEmpty) {
                     // For demo, we trigger manually or just rely on user finishing typing
                     // But let's add a button for "AI Categorize" to make it explicit demo feature
                  }
                },
                decoration: InputDecoration(
                  hintText: 'Describe your issue in detail...',
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none),
                  filled: true,
                  fillColor: Theme.of(context).inputDecorationTheme.fillColor,
                ),
                validator: (v) => v!.isEmpty ? 'Required' : null,
              ),
              const SizedBox(height: 8),
              Align(
                alignment: Alignment.centerRight,
                child: TextButton.icon(
                  onPressed: _isCategorizing ? null : _detectCategory,
                  icon: _isCategorizing 
                    ? const SizedBox(width: 12, height: 12, child: CircularProgressIndicator.adaptive(strokeWidth: 2)) 
                    : const Icon(Icons.auto_awesome, size: 16),
                  label: Text(_isCategorizing ? 'Analyzing...' : 'Auto-Categorize'),
                ),
              ),

              const SizedBox(height: 24),
              _buildSectionTitle('Category'),
              const SizedBox(height: 8),
              Wrap(
                spacing: 8,
                runSpacing: 8,
                children: HelpCategory.values.map((cat) {
                  final isSelected = _selectedCategory == cat;
                  return ChoiceChip(
                    label: Text(_categoryName(cat)),
                    selected: isSelected,
                    onSelected: (selected) => setState(() => _selectedCategory = selected ? cat : null),
                    selectedColor: Theme.of(context).primaryColor.withValues(alpha: 0.2),
                    backgroundColor: Theme.of(context).cardColor,
                    side: BorderSide(color: isSelected ? Theme.of(context).primaryColor : Colors.grey.shade300),
                    labelStyle: TextStyle(
                      color: isSelected ? Theme.of(context).primaryColor : Colors.black87,
                      fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
                    ),
                  );
                }).toList(),
              ),



              const SizedBox(height: 24),
              _buildSectionTitle('Location'),
              const SizedBox(height: 8),
              Container(
                height: 150,
                width: double.infinity,
                decoration: BoxDecoration(
                  color: Colors.grey[200],
                  borderRadius: BorderRadius.circular(16),
                  image: (_permission == LocationPermission.always || _permission == LocationPermission.whileInUse) 
                  ? const DecorationImage(
                    image: NetworkImage('https://maps.googleapis.com/maps/api/staticmap?center=37.7749,-122.4194&zoom=14&size=600x300&markers=color:red%7C37.7749,-122.4194&key=AIzaSyBObagDSkGta1Jv7hwRgL9DX2UxvLQQJnY'),
                    fit: BoxFit.cover,
                  ) : null,
                ),
                child: Center(
                  child: (_permission == LocationPermission.always || _permission == LocationPermission.whileInUse)
                  ? Container(
                    padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(20),
                      boxShadow: [BoxShadow(color: Colors.black.withValues(alpha: 0.1), blurRadius: 4)],
                    ),
                    child: const Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Icon(Icons.location_on, color: Colors.red, size: 16),
                        SizedBox(width: 4),
                        Text('Current Location', style: TextStyle(fontWeight: FontWeight.bold)),
                      ],
                    ),
                  )
                  : Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        const Icon(Icons.location_off, color: Colors.grey, size: 32),
                        const SizedBox(height: 8),
                        Text(
                          'Location permission not given',
                          style: TextStyle(color: Colors.grey[600], fontWeight: FontWeight.bold),
                        ),
                        TextButton(
                          onPressed: _checkPermission,
                          child: const Text('Retry Permission'),
                        ),
                      ],
                    ),
                ),
              ),
              
              const SizedBox(height: 24),
              _buildSectionTitle('Urgency'),
              const SizedBox(height: 8),
              Slider(
                value: _selectedUrgency.index.toDouble(),
                min: 0,
                max: 3,
                divisions: 3,
                label: _urgencyName(_selectedUrgency),
                activeColor: _urgencyColor(_selectedUrgency),
                onChanged: (val) {
                  setState(() => _selectedUrgency = UrgencyLevel.values[val.toInt()]);
                },
              ),
              Center(
                child: Text(
                  _urgencyName(_selectedUrgency).toUpperCase(),
                  style: TextStyle(
                    color: _urgencyColor(_selectedUrgency),
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),

              const SizedBox(height: 32),
              PrimaryButton(
                text: 'Post Request',
                isLoading: _isLoading,
                onPressed: _submitRequest,
              ),
              const SizedBox(height: 32),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Text(
      title,
      style: GoogleFonts.poppins(
        fontSize: 16,
        fontWeight: FontWeight.w600,
        color: Colors.black87,
      ),
    );
  }

  String _categoryName(HelpCategory cat) {
    return cat.toString().split('.').last.toUpperCase();
  }

  String _urgencyName(UrgencyLevel level) {
    return level.toString().split('.').last;
  }

  Color _urgencyColor(UrgencyLevel level) {
    switch (level) {
      case UrgencyLevel.low: return Colors.green;
      case UrgencyLevel.medium: return Colors.orange;
      case UrgencyLevel.high: return Colors.deepOrange;
      case UrgencyLevel.critical: return Colors.red;
    }
  }
}
